config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resource :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :index, :edit, :update] do
    resource :follows, only: [:create, :destroy]
    get "followings" => "follows#followings", as: "followings"
    get "followers" => "follows#followers", as: "followers"
  end

  resources :chats, only: [:show, :create]

  resources :groups, only: [:index, :show, :edit, :create, :update, :new, :show]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  get "search" => "searches#search"

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :view_counts, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :tag,presence:true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == "perfect"
      Book.where(title: content)
    elsif method == "forward"
      Book.where("title LIKE ?", content + "%")
    elsif method == "backward"
      Book.where("title LiKE ?", "%" + content)
    else
      Book.where("title LIKE ?", "%" + content + "%")
    end
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :image
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users
  has_many :groups, through: :group_users

  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_many :revers_of_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy

  has_many :followers, through: :revers_of_follows, source: :follower
  has_many :followings, through: :follows, source: :followed

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  has_many :view_counts, dependent: :destroy

  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end


  def follow(user_id)
    follows.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follows.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

  def self.search_for(content, method)
    if method == "perfect"
      User.where(name: content)
    elsif method == "forward"
      User.where("name LIKE ?", content + "%")
    elsif method == "backward"
      User.where("name LiKE ?", "%" + content)
    else
      User.where("name LIKE ?", "%" + content + "%")
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment_form.html.erb
<%= form_with model: [@book,@post_comment], local: false do |f| %>
  <%= f.text_area :comment, size:"90x5" %><br>
  <%= f.submit '送信'%>
<% end %>

app/views/comments/_post_comments.html.erb
<table>
  <% @book.post_comments.each do |post_comment| %>
    <% post_comment_user = post_comment.user %>
    <tr>
      <td>
      <%= link_to user_path(post_comment_user), class: "user_#{post_comment_user.id}" do %>
        <%= image_tag post_comment.user.get_profile_image(100,100) %><br>
        <%= post_comment_user.name %>
      <% end %>
      </td>
      <td><%= post_comment.comment %></td>
      <% if current_user == post_comment_user %>
      <td class="comment-delete">
        <%= link_to 'Destroy', book_post_comments_path(post_comment.book_id, post_comment.id), class: 'btn-sm btn-danger', method: :delete, local: true %>
      </td>
    <% end %>
    </tr>
  <% end %>
</table>

app/views/comments/create.js.erb
alert('アラートのメッセージ')
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.post_comments.count %>");
$(".comments_area").html("<%= j(render 'comment/post_comments', book: @book, post_comment: @post_comment) %>");
$("#post_comment_comment").val("");

app/views/comments/destroy.js.erb
alert('アラートのメッセージ')
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.post_comments.count %>");
$(".comments_area").html("<%= j(render 'comment/post_comments', book: @book, post_comment: @post_comment) %>");
$("#post_comment_comment").val("");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-link User px-2">
                  <%= link_to user_path(current_user.id), class: "text-light text-decoration-none" do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li class="nav-link User px-2">
                  <%= link_to users_path, class: "text-light text-decoration-none" do %>
                    <i class="fas fa-users"></i> Users
                  <% end %>
                </li>
                <li class="nav-link User px-2">
                  <%= link_to books_path, class: "text-light text-decoration-none" do %>
                    <i class="fas fa-book-open"></i> Books
                  <% end %>
                </li>
                <li class="nav-link User px-2">
                  <%= link_to destroy_user_session_path, method: :delete, class: "text-light text-decoration-none" do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li class="nav-link User px-2">
                  <%= link_to root_path, class: "text-light text-decoration-none" do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li class="nav-link User px-2">
                  <%= link_to home_about_path, class: "text-light text-decoration-none" do %>
                    <i class="fas fa-link"></i> About
                  <% end %>
                </li>
                <li class="nav-link User px-2">
                  <%= link_to new_user_registration_path, class: "text-light text-decoration-none" do %>
                    <i class="fas fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li class="nav-link User px-2">
                  <%= link_to new_user_session_path, class: "text-light text-decoration-none" do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <% if user_signed_in? %>
      <div class="text-center mt-2">
        <%= form_with url: search_path, method: :get, local: true do |f| %>
          <%= f.text_field :content %>
          <%= f.select :model, options_for_select({ "User" => "user", "Book" => "book"}) %>
          <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial"}) %>
          <%= f.submit "検索" %>
        <% end %>
      </div>
      <% end %>
    </header>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>