config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resource :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :index, :edit, :update] do
    resource :follows, only: [:create, :destroy]
    get "followings" => "follows#followings", as: "followings"
    get "followers" => "follows#followers", as: "followers"
  end

  resources :chats, only: [:show, :create]

  resources :groups, only: [:index, :show, :edit, :create, :update, :new, :show]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  get "search" => "searches#search"

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :view_counts, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :tag,presence:true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == "perfect"
      Book.where(title: content)
    elsif method == "forward"
      Book.where("title LIKE ?", content + "%")
    elsif method == "backward"
      Book.where("title LiKE ?", "%" + content)
    else
      Book.where("title LIKE ?", "%" + content + "%")
    end
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :image
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users
  has_many :groups, through: :group_users

  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_many :revers_of_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy

  has_many :followers, through: :revers_of_follows, source: :follower
  has_many :followings, through: :follows, source: :followed

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  has_many :view_counts, dependent: :destroy

  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end


  def follow(user_id)
    follows.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follows.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

  def self.search_for(content, method)
    if method == "perfect"
      User.where(name: content)
    elsif method == "forward"
      User.where("name LIKE ?", content + "%")
    elsif method == "backward"
      User.where("name LiKE ?", "%" + content)
    else
      User.where("name LIKE ?", "%" + content + "%")
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    puts "作成したキー #{ENV['SECRET_KEY']}"
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @books = Book.all.sort { |a, b|
      b.favorites.where(created_at: from...to).size <=>
      a.favorites.where(created_at: from...to).size
    }
    @book = Book.new
  end

  def create
    @user = User.find(current_user.id)
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_new = Book.new
    @post_comment = PostComment.new
    @book_detail = Book.find(params[:id])
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book_detail.id)
      current_user.view_counts.create(book_id: @book_detail.id)
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
    @user = User.find(current_user.id)
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body, :tag)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tag_searches_helper.rb
module TagSearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_favorites.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete do %>
    <i class="fas fa-heart"></i><%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post do %>
    <i class="far fa-heart"></i><%= book.favorites.count %>
  <% end %>
<% end %>

app/views/books/_static_rate.html.erb
<div id="rate_<%= book.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
    let raty_<%= book.id %> = document.querySelector('#rate_<%= book.id %>');
    rate_<%= book.id %>.innerHTML = ""
    let option_<%= book.id %> = {
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        readOnly: true,
      };
    raty(raty_<%= book.id %> ,option_<%= book.id %>);
});
</script>

app/views/books/_userinfo.html.erb
<h2>User info</h2>
<%= image_tag current_user.get_profile_image(100, 100) %>
<table class="table">
  <tr>
    <th>name</th>
    <th><%= current_user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= current_user.introduction %></th>
  </tr>
</table>
<%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do %>
  <i class="fas fa-user-cog"></i>
<% end %>

<h2 class="mt-3">New book</h2>

<%= form_with model: Book.new do |f| %>
<div class="form-group">
  <label for="book-title">Title</label>
  <p><%= f.text_field :title, class: "form-control" %></p>
</div>
<div class="form-group">
  <label for="book-opinion">Opinion</label>
  <p><%= f.text_area :body, class: "form-control" %></p>
</div>
<div class="form-group">
  <%= f.label :Tag %>
  <%= f.text_field :tag, class: 'form-control book_tag' %>
</div>

  <div class="form-group" id="star">
    <%= f.label :rate %>
    <%= f.hidden_field :rate, id: :review_star, class:'form-control' %>
  </div>
  <div id="post_raty"></div>
  <script>
    $(document).on('turbolinks:load', function() {
    let raty_elem = document.querySelector('#post_raty');
    raty_elem.innerHTML = ""
    let option = {
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        scoreName: 'book[rate]',
      };
    raty(raty_elem,option);
    });
  </script>

<div class="form-group">
  <%= f.submit 'Create Book', {class: "btn btn-success"} %>
</div>
<% end %>

app/views/books/edit.html.erb
<p></p>
<div class="container"> 
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <label for="book-title">Title</label>
        <%= f.text_field :title, value: @book.title, class: "form-control title" %>
      </div>
      <div class="form-group">
        <label for="book-opinion">Opinion</label>
        <%= f.text_area :body, value: @book.body, class: "form-control opinion" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>
      <% end %>
      <%= link_to "Show", book_path %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p></p>
<div class="container px-5 px-sm-0">
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="row">
  <div class="col-md-3">
    <%= render 'userinfo', books: @books %>
  </div>

  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
      <table class="table table-hover">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th>Tag</th>
          <th></th>
          <th></th>
        </tr>

      <% @books.each do |book| %>
        <tr id="book_<%= book.id %>">
          <th>
            <%= link_to user_path(book.user_id) do %>
              <%= image_tag book.user.get_profile_image(100, 100) %>
            <% end %>
          </th>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td><%= book.tag %></td>
          <td class="favorites-btn">
            <%= render 'favorites/favorites-btn', book: book %>
          </td>
          <td>コメント件数：<%= book.post_comments.count %></td>
          <td>閲覧数:<%= book.view_counts.count %></td>
          <td><%= render "books/static_rate", book: book %></td>
          </th>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p>
  <%= flash[:notice] %>
</p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(100, 100) %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>
      <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: Book.new do |f| %>
      <div class="form-group">
        <label for="book-title">Title</label>
        <p><%= f.text_field :title, class: "form-control" %></p>
      </div>
      <div class="form-group">
        <label for="book-opinion">Opinion</label>
        <p><%= f.text_area :body, class: "form-control" %></p>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book', {class: "btn btn-success"} %>
      </div>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
      <tr>
        <td>
          <%= link_to user_path(@book.user_id) do %>
            <%= image_tag @book.user.get_profile_image(100, 100) %>
            <p><%= @book.user.name %></P>
          <% end %>
        </td>
        <td><%= link_to @book.title, book_path(@book.id) %></td>
        <td><%= @book.body %></td>
        <td class="comments-count">コメント数：<%= @book.post_comments.count %></td>
        <td class="view-count">閲覧数:<%= @book_detail.view_counts.count %></td>
        <% if @book.user_id == current_user.id %>
        <td>
          <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
        </td>
        <td>
          <%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-sm btn-danger",
          "data-confirm" => "本当に消しますか？" %>
        </td>
        <% end %>
      </tr>
    </table>
    <div id="comments_area">
      <%= render 'comments/post_comments', book: @book %>
    </div>
    <div>
      <%= render 'comments/comment_form', book: @book, post_comment: @post_comment %>
    </div>
  </div>
</div>